### ISSUE TITLE
Android 6.0: no possibility to "download all" lessons like for iOS? The button is missing!

### ISSUE THREAD

**Issue by bufemc** [language-transfer/lt-app#30]
I own phones with both OS, iOS and Android. On iOS there is a button on top of a course "Download all xx lessons" if you didn't download them already. However, this button does NOT show up on Android. I am confused if this is intentional, or just an issue with my device, which is:

LG G4
Android 6.0

I also tried to delete everything (although I did not download anything before) e.g. for the course "Spanish" via "Data management", but that didn't help. For your motivation I rated the iOS app 5 stars ;-)

Other ideas what could go wrong, just thoughts and guesses:

- the button is there but another UI element is drawn over it?
- internal variables have a wrong state that it was already downloaded?
- it's really missing on Android?
- device specific problem

Suspicious is the still open PR and e.g. this:
https://github.com/language-transfer/lt-app/blob/master/js/components/AllLessons/LessonRow.react.js

```
        <View style={styles.downloadBox}>
          {ready
            ? renderDownloadProgress(downloaded, downloadState, downloading)
            : null}
        </View>
```

Screenshot Android 6.0 on LG G4:
![image](https://user-images.githubusercontent.com/18305092/91062234-bf42d880-e62c-11ea-8117-7e178e26198f.png)

**Comment by SyntaxBlitz** [comment]
Indeed #27 will fix this :) The iOS build is actually on the #27 branch, which is why it has the button even though Android doesn't have it yet.

We originally decided to hold off on introducing the "Download all lessons" button to the app, just because this was the first time we were offering direct downloads of the LT courses (used to be you needed to use SoundCloud, YouTube, or a torrent), and we weren't sure how much it would cost in bandwidth. We decided to require the user to download each file individually (an admittedly worse UX) to trade off against the people who would download all the files without using them. Since the app doesn't (and never will) pull in revenue, it was important to us to minimize costs.

But! After looking at usage, we decided a "download all" button really won't break the bank, and that's why it ended up in the iOS build. I haven't gotten a chance to tie up the loose ends on #27 yet which is why it hasn't been merged and built for Android, but I'm hoping to get it done soon (I've recently started a new job, and in light of a few other changes in my personal life I've needed to shift focus for a bit).

**Comment by bufemc** [comment]
At least there is an explanation, thank you. My first thought was that maybe the button is hidden or something is painted over etc.

**Comment by bufemc** [comment]
Guess who tapped 90 times on each of the Spanish lessons to download now? ,) Would be nice if the "download all" button arrives in Android versions soon, too!

**Comment by bufemc** [comment]
Any progress? Another idea: one could show how many times a track has been played. So if I played 3 times the tracks 1 to 7 when bicycling, but only 2 times track 8 to 10, I could relisten to the latter.

**Comment by hackel** [comment]
The Download All button now appears on Android in v1.1, but it doesn't seem to do anything.  It shows a dialogue to confirm the download size, but after clicking OK, nothing happens.  Individual downloads still work fine.

**Comment by SyntaxBlitz** [comment]
huh... thanks for mentioning this, @hackel! It's a one-line fix, I don't know how this made it into master (since I have a pretty good memory of testing it as I was developing). I'll try to get a fix up soon.

**Comment by bufemc** [comment]
I guess you forgot to close this issue. It seems meanwhile to be fixed. On my LG4 I could use in "All lessons" the "Download All" button for music theory and it worked.

**Comment by SyntaxBlitz** [comment]
ah yes! thanks for pointing that out. closing this out :)
